services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: meuuser
      POSTGRES_PASSWORD: meusenha
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/meubanco
      SPRING_DATASOURCE_USERNAME: meuuser
      SPRING_DATASOURCE_PASSWORD: meusenha
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata: